language: python
dist: focal  
python:
  - "3.10"   

before_install:
  - sudo apt-get update

install:
  - pip install aiohttp telebot pymongo pytz psutil

script:
  - chmod +x * && chmod +x Pawan && python3 danger.py
